# Configuration for ddclient

# Protocol can be dyndns2, noip, etc.
protocol=noip

# Use 'if' to get IP from a specific interface
use=if, if=wlan0

# Server to update
server=dynupdate.no-ip.com

# Login credentials
login=your_noip_username
password='your_noip_password'

# Hostname to update
your_hostname.ddns.net
