#!/bin/sh
# cloudflared-setup.sh — Convert a Cloudflare tunnel token into a local
# credentials.json + config.yml.  Also ensures the device HTTPS server
# certificate has a unique CN (derived from the RPi3 CPU serial number) and
# a SAN matching the public domain, so mTLS can identify this specific device.
#
# Run as ExecStartPre in cloudflared.service — idempotent (skips if already done).

CONF_DIR=/etc/cloudflared
CONFIG="$CONF_DIR/config.yml"
CREDS="$CONF_DIR/credentials.json"

# Check if already configured AND has the mTLS client cert settings
if [ -f "$CREDS" ] && [ -f "$CONFIG" ]; then
    # If config exists but doesn't have mTLS settings, force regeneration
    if grep -q "originClientCertificate" "$CONFIG" 2>/dev/null; then
        exit 0
    fi
    # Otherwise, config exists but is outdated — fall through to regenerate
    echo "[cloudflared-setup] Updating config to enable mTLS..."
fi

# Source the environment to get CLOUDFLARE_TUNNEL_TOKEN
# shellcheck disable=SC1091
. "$CONF_DIR/env"

if [ -z "$CLOUDFLARE_TUNNEL_TOKEN" ]; then
    echo "[cloudflared-setup] ERROR: CLOUDFLARE_TUNNEL_TOKEN not set in $CONF_DIR/env" >&2
    exit 1
fi

# Read the public domain (skip comment lines, strip whitespace)
DOMAIN=$(grep -v '^#' "$CONF_DIR/domain" | head -n 1 | tr -d '[:space:]')
if [ -z "$DOMAIN" ]; then
    echo "[cloudflared-setup] ERROR: No domain configured in $CONF_DIR/domain" >&2
    exit 1
fi
echo "[cloudflared-setup] Domain: $DOMAIN"

# ── Derive a unique device ID from the RPi3 CPU serial number ────────────────
# /proc/cpuinfo exposes the hardware serial on Raspberry Pi.  Strip leading
# zeros and prefix with 'rpi3-' to form a valid CN component.
DEVICE_SERIAL=$(grep -m1 '^Serial' /proc/cpuinfo 2>/dev/null | awk '{print $3}' | sed 's/^0*//')
if [ -z "$DEVICE_SERIAL" ]; then
    # Fallback: use the wlan0 MAC address (remove colons)
    DEVICE_SERIAL=$(cat /sys/class/net/wlan0/address 2>/dev/null | tr -d ':')
fi
if [ -z "$DEVICE_SERIAL" ]; then
    # Last resort: use eth0 MAC address
    DEVICE_SERIAL=$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d ':')
fi
if [ -z "$DEVICE_SERIAL" ]; then
    echo "[cloudflared-setup] ERROR: Cannot determine a unique device serial" >&2
    exit 1
fi
DEVICE_ID="rpi3-${DEVICE_SERIAL}"
echo "[cloudflared-setup] Device ID: $DEVICE_ID"

# Persist the device ID so other components (e.g. BlockchainLogger) can read it.
echo "$DEVICE_ID" > /etc/iot-gateway/device-id
chmod 644 /etc/iot-gateway/device-id

# ── Verify server certificate (generated by CertificateManager on first boot) ─
# CertificateManager now reads /etc/cloudflared/domain and /proc/cpuinfo at
# startup to generate server.crt with CN=DEVICE_ID and SAN=DOMAIN directly,
# so no regeneration is needed here.  We just confirm the cert exists before
# proceeding — if it is missing, something went wrong with the iot-gateway
# service and we should abort rather than proceed with a broken setup.
SERVER_CERT=/etc/https-server/server.crt
if [ ! -f "$SERVER_CERT" ]; then
    echo "[cloudflared-setup] ERROR: $SERVER_CERT not found." >&2
    echo "[cloudflared-setup] Check that iot-gateway.service started successfully." >&2
    exit 1
fi
echo "[cloudflared-setup] Server cert verified: $SERVER_CERT"

# ── Decode the base64 tunnel token to JSON ──────────────────────────────────
# Strip any whitespace / carriage-returns that may appear in the env file.
TOKEN=$(printf '%s' "$CLOUDFLARE_TUNNEL_TOKEN" | tr -d '[:space:]')

echo "[cloudflared-setup] DEBUG: token='$TOKEN'"


# The token may lack base64 padding — add it if needed.
MOD=$(( ${#TOKEN} % 4 ))
if [ "$MOD" -ne 0 ]; then
    PAD=$(( 4 - MOD ))
    i=0; PADDING=""
    while [ $i -lt $PAD ]; do PADDING="${PADDING}="; i=$(( i + 1 )); done
    TOKEN="${TOKEN}${PADDING}"
fi

# Try native base64 first; fall back to openssl (more reliable on BusyBox).
TOKEN_JSON=$(printf '%s\n' "$TOKEN" | base64 -d 2>/dev/null)
if [ -z "$TOKEN_JSON" ] && command -v openssl >/dev/null 2>&1; then
    TOKEN_JSON=$(printf '%s\n' "$TOKEN" | openssl base64 -d -A 2>/dev/null)
fi
if [ -z "$TOKEN_JSON" ]; then
    echo "[cloudflared-setup] ERROR: Failed to base64-decode the tunnel token" >&2
    echo "[cloudflared-setup] DEBUG: base64 available=$(command -v base64 2>/dev/null || echo no)" >&2
    echo "[cloudflared-setup] DEBUG: token length=${#TOKEN}" >&2
    exit 1
fi

# ── Extract fields from the compact JSON: {"a":"...","t":"...","s":"..."} ───
ACCOUNT=$(printf '%s' "$TOKEN_JSON" | sed 's/.*"a":"\([^"]*\)".*/\1/')
UUID=$(printf '%s'    "$TOKEN_JSON" | sed 's/.*"t":"\([^"]*\)".*/\1/')
SECRET=$(printf '%s'  "$TOKEN_JSON" | sed 's/.*"s":"\([^"]*\)".*/\1/')

if [ -z "$ACCOUNT" ] || [ -z "$UUID" ] || [ -z "$SECRET" ]; then
    echo "[cloudflared-setup] ERROR: Could not parse token fields (a/t/s)" >&2
    echo "[cloudflared-setup] Raw JSON: $TOKEN_JSON" >&2
    exit 1
fi

# ── Write credentials.json ───────────────────────────────────────────────────
cat > "$CREDS" <<EOF
{
  "AccountTag":   "$ACCOUNT",
  "TunnelSecret": "$SECRET",
  "TunnelID":     "$UUID"
}
EOF
chmod 600 "$CREDS"

# ── Write config.yml ─────────────────────────────────────────────────────────
# caPool: cloudflared verifies the device's server certificate against the
#   local Root CA (/etc/https-server/root-ca.crt), replacing the insecure
#   noTLSVerify=true.  This provides device identification: only an RPi3 that
#   holds a server certificate signed by our Root CA will be trusted.
# originServerName: must match the CN/SAN on the device's server.crt.
#   Set to the public domain so the TLS SNI check passes.
# caPool for mTLS client cert (device identity outbound): when the
#   backend architecture is added, uncomment originClientCertificate and
#   originClientKey so the device presents client.crt to prove its identity.
cat > "$CONFIG" <<EOF
tunnel: $UUID
credentials-file: $CREDS

ingress:
  - hostname: $DOMAIN
    service: https://localhost:8443
    originRequest:
      caPool: /etc/https-server/root-ca.crt
      originServerName: $DOMAIN
      # Enable full mTLS (device presents client cert to backend):
      originClientCertificate: /etc/https-server/client.crt
      originClientKey: /etc/https-server/client.key
  - service: http_status:404
EOF
chmod 600 "$CONFIG"

echo "[cloudflared-setup] Configured: $DOMAIN -> https://localhost:8443 (TLS verified via Root CA)"
echo "[cloudflared-setup] Tunnel UUID: $UUID"
